import test from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  bumpVersion,
  captureFileSnapshots,
  revertVersionChanges,
  transformHttpScanServerSource,
} from '../scripts/publish.js';

test('bumpVersion increments supported semver segments', () => {
  assert.equal(bumpVersion('1.2.3', 'major'), '2.0.0');
  assert.equal(bumpVersion('1.2.3', 'minor'), '1.3.0');
  assert.equal(bumpVersion('1.2.3', 'patch'), '1.2.4');
});

test('bumpVersion rejects invalid bump types', () => {
  assert.throws(() => bumpVersion('1.2.3', 'ptach'), /Invalid version bump type/);
});

test('bumpVersion rejects invalid version formats', () => {
  assert.throws(() => bumpVersion('1.2', 'patch'), /Invalid version/);
  assert.throws(() => bumpVersion('1.two.3', 'patch'), /Invalid version/);
});

test('revertVersionChanges restores original file contents and removes new files', async () => {
  const tempDir = await mkdtemp(join(tmpdir(), 'smart-terminal-mcp-'));
  const existingFile = join(tempDir, 'package.json');
  const createdLater = join(tempDir, 'server-card.json');

  try {
    await writeFile(existingFile, 'original');

    const snapshots = captureFileSnapshots([existingFile, createdLater]);

    await writeFile(existingFile, 'updated');
    await writeFile(createdLater, 'generated');

    revertVersionChanges(snapshots);

    assert.equal(await readFile(existingFile, 'utf8'), 'original');
    await assert.rejects(access(createdLater), /ENOENT/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('transformHttpScanServerSource rewrites SERVER_CARD using AST and is idempotent', () => {
  const source = [
    "import http from 'node:http';",
    "import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';",
    '',
    '// Static server card for Smithery scanning',
    'const SERVER_CARD =',
    '  {',
    "    serverInfo: { name: 'smart-terminal-mcp', version: '1.2.3' },",
    '    tools: [],',
    '  };',
    '',
    'export { SERVER_CARD };',
    '',
  ].join('\n');

  const transformed = transformHttpScanServerSource(source);
  assert.equal(transformed.changed, true);
  assert.match(transformed.code, /import \{ readFileSync \} from ['"]node:fs['"];?/);
  assert.match(transformed.code, /Server card is auto-generated by publish\.js/);
  assert.doesNotMatch(transformed.code, /Static server card for Smithery scanning/);
  assert.match(transformed.code, /const SERVER_CARD = JSON\.parse\(readFileSync\(new URL\('\.\.\/server-card\.json', import\.meta\.url\), 'utf8'\)\);/);

  const rerun = transformHttpScanServerSource(transformed.code);
  assert.equal(rerun.changed, false);
  assert.equal(rerun.code, transformed.code);
});

test('transformHttpScanServerSource extends existing fs imports without duplicating them', () => {
  const source = [
    "import http from 'node:http';",
    "import { writeFileSync } from 'node:fs';",
    '',
    'const SERVER_CARD = { tools: [] };',
    '',
  ].join('\n');

  const transformed = transformHttpScanServerSource(source);
  assert.equal(transformed.changed, true);
  assert.match(transformed.code, /import \{ writeFileSync, readFileSync \} from ['"]node:fs['"];?/);
  assert.doesNotMatch(transformed.code, /import \{ readFileSync \} from ['"]node:fs['"];?\s*import \{ writeFileSync, readFileSync \} from ['"]node:fs['"];?/);
});
