# Generated by Smithery (refined for PTY support)
FROM node:20-slim
# Install build tools for native node-pty
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production
COPY . .
# For stdio-based MCP, CMD should just run the index
CMD ["node", "src/index.js"]
